graph TD
    RACK[Mechanical Rack Assembly]:::project
    PSU[Power Supply Module]:::project
    NOISE[White Noise Generator]:::project

    RACK --> PSU --> NOISE

    classDef project fill:#d9b3ff,stroke:#333;

    %% Clickable links using full GitHub URLs for direct rendering
    click RACK "https://github.com/elandahl/eurorack-course/blob/main/project/01-mechanical-rack/README.md" "View mechanical rack module"
    click PSU "https://github.com/elandahl/eurorack-course/blob/main/project/02-power-supply/README.md" "View power supply module"
    click NOISE "https://github.com/elandahl/eurorack-course/blob/main/project/03-white-noise-generator/README.md" "View white noise generator module"

